import type { Metadata, Viewport } from 'next';
import { IBM_Plex_Mono, IBM_Plex_Sans_Condensed } from 'next/font/google';
import GlobalProvider from '@/components/providers/GlobalProvider';
import 'react-loading-skeleton/dist/skeleton.css';
import './globals.css';

const ibmPlexSans = IBM_Plex_Sans_Condensed({
  variable: '--font-ibm-plex-sans',
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700'],
});

const ibmPlexMono = IBM_Plex_Mono({
  variable: '--font-ibm-plex-mono',
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700'],
});

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: {
    default: 'ZoraBot',
    template: '%s | ZoraBot',
  },
  openGraph: {
    title: {
      default: 'ZoraBot',
      template: '%s | ZoraBot',
    },
  },
};

export const viewport: Viewport = {
  userScalable: false,
  themeColor: '#0a0a0a',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${ibmPlexSans.variable} ${ibmPlexMono.variable} antialiased`}>
        <GlobalProvider>{children}</GlobalProvider>
      </body>
    </html>
  );
}
